modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/Mrbysco/DrippedOut/issues"
license="MIT"

[[mods]]
modId="drippedout"
version="${file.jarVersion}"
displayName="DrippedOut"
displayURL="https://www.curseforge.com/minecraft/mc-mods/drippedout"
authors="Mrbysco, Darkosto"
description='''
What do you call it when a stalagmite and a stalactite finally bump into each other in the center of a cave?

A stala-fight.
'''
[[dependencies.drippedout]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.20.4,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.drippedout]]
modId="neoforge"
type="REQUIRED"
versionRange="[20.2.59-beta,)"
ordering="NONE"
side="BOTH"